
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-cicd
  labels:
    app: test-cicd
spec:
  selector:
    matchLabels:
      app: test-cicd
  template:
    metadata:
      labels:
        app: test-cicd
    spec:
      containers:
        - name: test-cicd
          image: ghcr.io/harry-zhangkai/test-cicd:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "default"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: github-registry-secret-harry